import { Country } from '@hemager/api-types';
import type { Seeder } from '../types';

const seedContestants = [
  {
    id: '2mRBPZjqTf_Q30w--9uqO',
    firstname: 'John',
    surname: 'Doe',
    clubId: 'X23m7cPHtxc8JM9r6RxGT',
    birthdate: new Date('2000-01-01'),
    gender: 'male',
    rating: 1500,
    nationality: Country.CzechRepublic,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'wc5xzT90ajHj0bjxuuURb',
    firstname: 'Pepa',
    surname: 'Doe',
    clubId: 'X23m7cPHtxc8JM9r6RxGT',
    birthdate: new Date('2000-01-01'),
    gender: 'male',
    rating: 900,
    nationality: Country.CzechRepublic,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'C_1h6Wt6bhiatPokd29jf',
    firstname: 'Martin',
    surname: 'Peterson',
    clubId: 'IbassxWXafTl5icqes8eU',
    birthdate: new Date('1999-01-01'),
    gender: 'male',
    rating: 2000,
    nationality: Country.CzechRepublic,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'A9XyZTqkHf1u3T4N9vMpX',
    firstname: 'Sophia',
    surname: 'Clark',
    clubId: 'IbassxWXafTl5icqes8eU',
    birthdate: new Date('1995-06-15'),
    gender: 'female',
    rating: 1700,
    nationality: Country.CzechRepublic,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'ZkX5PbXtqf_yQW9nTu8RpL',
    firstname: 'Emily',
    surname: 'Johnson',
    clubId: 'X23m7cPHtxc8JM9r6RxGT',
    birthdate: new Date('2002-03-10'),
    gender: 'female',
    rating: 1100,
    nationality: Country.CzechRepublic,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'BxR6WpXt3yQfMv0Ru9UpLQ',
    firstname: 'Ethan',
    surname: 'Brown',
    clubId: 'IbassxWXafTl5icqes8eU',
    birthdate: new Date('1998-09-05'),
    gender: 'male',
    rating: 1400,
    nationality: Country.CzechRepublic,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'Xb5zRbYTqG_j4Qp8M9UkPL',
    firstname: 'Oliver',
    surname: 'Davis',
    clubId: 'X23m7cPHtxc8JM9r6RxGT',
    birthdate: new Date('2001-11-20'),
    gender: 'male',
    rating: 1300,
    nationality: Country.CzechRepublic,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'NyWpRtZXvF4q3b5pM9uLQK',
    firstname: 'Lucas',
    surname: 'Miller',
    clubId: 'IbassxWXafTl5icqes8eU',
    birthdate: new Date('2003-04-08'),
    gender: 'male',
    rating: 1200,
    nationality: Country.CzechRepublic,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'TkX7PbRqW5f0MvYTn9Up4L',
    firstname: 'Amelia',
    surname: 'Wilson',
    clubId: 'X23m7cPHtxc8JM9r6RxGT',
    birthdate: new Date('2000-12-12'),
    gender: 'female',
    rating: 1600,
    nationality: Country.CzechRepublic,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'PxL6WbX5RYTq4QNv0MUpLk',
    firstname: 'Mason',
    surname: 'Moore',
    clubId: 'IbassxWXafTl5icqes8eU',
    birthdate: new Date('1997-08-21'),
    gender: 'male',
    rating: 1800,
    nationality: Country.CzechRepublic,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'QkR5bWXyZN3Tq0pMV9UpPL',
    firstname: 'Ella',
    surname: 'Taylor',
    clubId: 'X23m7cPHtxc8JM9r6RxGT',
    birthdate: new Date('1996-02-14'),
    gender: 'female',
    rating: 900,
    nationality: Country.CzechRepublic,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const up: Seeder = async ({ context: sequelize }) => {
  await sequelize.getQueryInterface().bulkInsert('Contestant', seedContestants);
};
export const down: Seeder = async ({ context: sequelize }) => {
  await sequelize
    .getQueryInterface()
    .bulkDelete('Contestant', { id: seedContestants.map((u) => u.id) });
};
